draw_set_halign(fa_center);
draw_set_font(global.font);
draw_option(150, 30 + ScrollY, "BACK", optionselected == input_selected.back);
var _yy = 50;
var _x1 = 400;
var _x2 = 600;
draw_option(_x1, _yy + ScrollY, "UP", optionselected == input_selected.up);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.keybinds.key_up));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "RIGHT", optionselected == input_selected.right);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.keybinds.key_right));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "LEFT", optionselected == input_selected.left);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.keybinds.key_left));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "DOWN", optionselected == input_selected.down);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.keybinds.key_down));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "JUMP", optionselected == input_selected.jump);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.keybinds.key_jump));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "SLAP", optionselected == input_selected.slap);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.keybinds.key_slap));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "TAUNT", optionselected == input_selected.taunt);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.keybinds.key_taunt));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "ATTACK", optionselected == input_selected.attack);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.keybinds.key_attack));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "START", optionselected == input_selected.start);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.keybinds.key_start));
_yy += 50;
draw_set_font(global.smallfont);
draw_text(480, 512, subtitle);
